"""Published API contracts; source revisions are recorded in tests/parity-audit.json."""

TASK_PATH = "/nano-banana/tasks"

ENDPOINTS = {
    "nano_banana_generate_image": {
        "method": "POST",
        "path": "/nano-banana/images",
        "operation": "generate",
        "schema": {
            "type": "object",
            "required": ["action", "prompt"],
            "properties": {
                "action": {"enum": ["generate", "edit"], "type": "string"},
                "model": {
                    "type": "string",
                    "enum": [
                        "nano-banana",
                        "nano-banana-2-lite",
                        "nano-banana-2",
                        "nano-banana-2.1",
                        "nano-banana-pro",
                        "nano-banana:official",
                        "nano-banana-2-lite:official",
                        "nano-banana-2:official",
                        "nano-banana-pro:official",
                    ],
                },
                "prompt": {"type": "string"},
                "image_urls": {"type": "array", "items": {"type": "string"}},
                "count": {"type": "integer", "minimum": 1, "maximum": 4},
                "aspect_ratio": {
                    "type": "string",
                    "enum": ["1:1", "3:2", "2:3", "16:9", "9:16", "4:3", "3:4"],
                },
                "resolution": {"type": "string", "enum": ["1K", "2K", "4K"]},
                "callback_url": {"type": "string"},
                "async": {"type": "boolean"},
            },
        },
        "properties": {
            "action": {"enum": ["generate", "edit"], "type": "string"},
            "model": {
                "type": "string",
                "enum": [
                    "nano-banana",
                    "nano-banana-2-lite",
                    "nano-banana-2",
                    "nano-banana-2.1",
                    "nano-banana-pro",
                    "nano-banana:official",
                    "nano-banana-2-lite:official",
                    "nano-banana-2:official",
                    "nano-banana-pro:official",
                ],
            },
            "prompt": {"type": "string"},
            "image_urls": {"type": "array", "items": {"type": "string"}},
            "count": {"type": "integer", "minimum": 1, "maximum": 4},
            "aspect_ratio": {
                "type": "string",
                "enum": ["1:1", "3:2", "2:3", "16:9", "9:16", "4:3", "3:4"],
            },
            "resolution": {"type": "string", "enum": ["1K", "2K", "4K"]},
            "callback_url": {"type": "string"},
            "async": {"type": "boolean"},
        },
        "parameters": [],
        "defaults": {
            "model": "nano-banana-2-lite",
            "aspect_ratio": "1:1",
            "resolution": "1K",
            "count": 1,
        },
        "fixed": {"action": "generate"},
        "allow_empty": [],
        "query_actions": [],
        "media_response": True,
    },
    "nano_banana_edit_image": {
        "method": "POST",
        "path": "/nano-banana/images",
        "operation": "edit",
        "schema": {
            "type": "object",
            "required": ["action", "prompt"],
            "properties": {
                "action": {"enum": ["generate", "edit"], "type": "string"},
                "model": {
                    "type": "string",
                    "enum": [
                        "nano-banana",
                        "nano-banana-2-lite",
                        "nano-banana-2",
                        "nano-banana-2.1",
                        "nano-banana-pro",
                        "nano-banana:official",
                        "nano-banana-2-lite:official",
                        "nano-banana-2:official",
                        "nano-banana-pro:official",
                    ],
                },
                "prompt": {"type": "string"},
                "image_urls": {"type": "array", "items": {"type": "string"}},
                "count": {"type": "integer", "minimum": 1, "maximum": 4},
                "aspect_ratio": {
                    "type": "string",
                    "enum": ["1:1", "3:2", "2:3", "16:9", "9:16", "4:3", "3:4"],
                },
                "resolution": {"type": "string", "enum": ["1K", "2K", "4K"]},
                "callback_url": {"type": "string"},
                "async": {"type": "boolean"},
            },
        },
        "properties": {
            "action": {"enum": ["generate", "edit"], "type": "string"},
            "model": {
                "type": "string",
                "enum": [
                    "nano-banana",
                    "nano-banana-2-lite",
                    "nano-banana-2",
                    "nano-banana-2.1",
                    "nano-banana-pro",
                    "nano-banana:official",
                    "nano-banana-2-lite:official",
                    "nano-banana-2:official",
                    "nano-banana-pro:official",
                ],
            },
            "prompt": {"type": "string"},
            "image_urls": {"type": "array", "items": {"type": "string"}},
            "count": {"type": "integer", "minimum": 1, "maximum": 4},
            "aspect_ratio": {
                "type": "string",
                "enum": ["1:1", "3:2", "2:3", "16:9", "9:16", "4:3", "3:4"],
            },
            "resolution": {"type": "string", "enum": ["1K", "2K", "4K"]},
            "callback_url": {"type": "string"},
            "async": {"type": "boolean"},
        },
        "parameters": [],
        "defaults": {
            "model": "nano-banana-2-lite",
            "aspect_ratio": "1:1",
            "resolution": "1K",
            "count": 1,
        },
        "fixed": {"action": "edit"},
        "allow_empty": [],
        "query_actions": [],
        "media_response": True,
    },
    "nano_banana_task_retrieve": {
        "method": "POST",
        "path": "/nano-banana/tasks",
        "operation": "task",
        "schema": {
            "type": "object",
            "properties": {
                "id": {"type": "string"},
                "ids": {"type": "array", "items": {"type": "string"}},
                "action": {"enum": ["retrieve", "retrieve_batch"], "type": "string"},
            },
        },
        "properties": {
            "id": {"type": "string"},
            "ids": {"type": "array", "items": {"type": "string"}},
            "action": {"enum": ["retrieve", "retrieve_batch"], "type": "string"},
        },
        "parameters": [],
        "defaults": {"wait_seconds": 0},
        "fixed": {},
        "allow_empty": [],
        "query_actions": ["retrieve", "retrieve_batch", "list", "presets"],
        "media_response": False,
    },
    "nano_banana_tasks_retrieve_batch": {
        "method": "POST",
        "path": "/nano-banana/tasks",
        "operation": "batch",
        "schema": {
            "type": "object",
            "properties": {
                "id": {"type": "string"},
                "ids": {"type": "array", "items": {"type": "string"}, "minItems": 1},
                "action": {"enum": ["retrieve", "retrieve_batch"], "type": "string"},
            },
            "required": ["action", "ids"],
        },
        "properties": {
            "id": {"type": "string"},
            "ids": {"type": "array", "items": {"type": "string"}, "minItems": 1},
            "action": {"enum": ["retrieve", "retrieve_batch"], "type": "string"},
        },
        "parameters": [],
        "defaults": {},
        "fixed": {"action": "retrieve_batch"},
        "allow_empty": [],
        "query_actions": ["retrieve", "retrieve_batch", "list", "presets"],
        "media_response": False,
    },
}
